### ISSUE TITLE
unique_ptr<char[]>を使う

### ISSUE THREAD

**Issue by pandaman64** [kaityo256/cps#1]
Qiitaの記事を読んできました．

https://github.com/kaityo256/cps/blob/7b8667c4ae18d87a0e1656593c7b2a45a8ae2fe6/cps.cpp#L129
では，`std::unique_ptr<char>`で`new char[len]`を受けていますが，これは`delete []`ではなく`delete`を実行するので正しくメモリが解放されません．
`std::unique_ptr<char[]>`を使用すべきかと思います．

参考: https://cpprefjp.github.io/reference/memory/unique_ptr.html
の配列版・「new[]演算子で～」の部分

**Comment by kaityo256** [comment]
コメントをありがとうございます。おっしゃるとおりですので、修正しておきました。
